### ISSUE TITLE
Issue while importing .ics file dtstart vs dtend

### ISSUE THREAD

**Issue by aenario** [cozy/cozy-ical#32]
Original report : https://forum.cozy.io/t/calendar-import-ics/884/3
Caused by : https://github.com/cozy/cozy-ical/blob/master/src/index.coffee#L599

We check if dtend.details.length but then get dtstart.details[0]

**Comment by clochix** [comment]
It would be nice to take some time to make import more error prone : always check if objects are not null, and try catch exception, reporting to the user that import has failed on one event instead of cancelling the whole process.
Feel free to create another ticket if you think this is too big for this iteration.

**Comment by jsilvestre** [comment]
As mentioned, the real deal is to move to Firefox's ical lib. This has always been a short term solution, I don't see any interest keeping it, besides the transition period (we already have integration tests).

Gotta have a look at this, I now realize the comments are shitty, because I can't remember anymore why it's done this way (the current check might not be enough, but I recall it's relevant).

**Comment by frankrousseau** [comment]
Our version of the lib works for many cases. I'm not sure that moving to another young library would solve all our problem.

**Comment by clochix** [comment]
@jsilvestre Has this been fixed ?

**Comment by clochix** [comment]
Ping @jsilvestre looks like you fixed this some month ago, could we close this issue ?

**Comment by jsilvestre** [comment]
Yes we can!
